name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  test_Cypress:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Recover the secret
        run: |
            echo '${{ secrets.CREDENTIALS_E2E }}' > cypress/fixtures/credentials1.json
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Tests 2
        run: |
          cat cypress/fixtures/credentials1.json
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          browser: chrome
      - name: Uploading artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
