name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  test_Cypress:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Install dep
      run: npm install -D @playwright/test
    - name: Recover the secret
      run: |
          echo '${{ secrets.CREDENTIALS_E2E }}' > cypress/fixtures/credentials1.json
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@master
      with:
        name: allure-results
        path: allure-results
    - uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    - uses: peaceiris/actions-gh-pages@v2
      if: always()
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history